# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(
    ['backend\\app.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('backend/Utils/service_account_credentials.json', 'Utils/'),
        ('backend/Utils/client_secrets.json', 'Utils/'),
        ('backend/Utils/Oauth2.json', 'Utils/'),
        ('backend/Utils/config.py', 'Utils/'),
        ('backend/Utils/*', 'Utils/'),
        ('backend/Utils/images/contact_not_found.png', 'Utils/images/'),
        ('backend/Utils/images/contact_not_found_2.jpg', 'Utils/images/'),
        ('backend/Utils/images/contact_not_found_3.jpg', 'Utils/images/'),
        ('backend/Utils/images/contact_not_found_4.png', 'Utils/images/'),
        ('backend/Utils/images/fullscreen_newchat.png', 'Utils/images/'),
        ('backend/Utils/images/halfscreen_newchat.png', 'Utils/images/'),
        ('backend/Utils/images/new_chat.png', 'Utils/images/'),
        ('backend/Utils/images/new_chat2.jpg', 'Utils/images/'),
        ('backend/Utils/images/new_chat3.jpg', 'Utils/images/'),
        ('backend/Utils/images/new_chat4.jpg', 'Utils/images/'),
        ('backend/ssformat.docx', './')
    ],
    hiddenimports=[
        'google.oauth2',
        'google.oauth2.credentials',
        'google.oauth2.service_account',
        'googleapiclient.discovery',
        'googleapiclient.errors',
        'google_auth_oauthlib.flow',
        'google.auth.transport.requests',
        'google.auth.exceptions',
        'docx',
        'pandas',
        'numpy',
        'openpyxl',
        'tkinter',
        'tkinter.ttk',
        'tkinter.messagebox',
        'tkinter.filedialog',
        'PIL',
        'PIL.Image',
        'PIL.ImageTk',
        'datetime',
        'json',
        'os',
        'sys',
        'threading',
        'queue',
        'time',
        'logging',
        'cv2',
        'flask',
        'flask_cors',
        'werkzeug',
        'firebase_admin',
        'firebase_admin.firestore',
        'pyautogui',
        'pyperclip',
        'pywinauto',
        'comtypes',
        'comtypes.client',
        'pythoncom',
        'gspread',
        'pydrive2',
        'pydrive2.drive',
        'pydrive2.auth',
        'python_docx',
        'requests',
        'urllib3',
        'certifi',
        'charset_normalizer',
        'idna',
        'cryptography',
        'cffi',
        'pycparser',
        'six',
        'dateutil',
        'pytz',
        'pytweening',
        'pygetwindow',
        'pyrect',
        'pyscreeze',
        'mouseinfo',
        'pymsgbox',
        'typing_extensions',
        'email',
        'smtplib',
        'ssl',
        'pickle',
        'base64',
        'mimetypes',
        're',
        'shutil',
        'subprocess',
        'platform',
        'webbrowser',
        'functools',
        'logging.handlers',
        'google_auth_oauthlib.flow'
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
    optimize=0,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='SS_Automation',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=None,
)
