services:
  # Frontend service
  - type: web
    name: be-ss-automation-frontend
    env: docker
    region: singapore
    plan: free
    dockerfilePath: ./frontend/Dockerfile
    envVars:
      - key: VITE_API_URL
        value: https://be-ss-automation.onrender.com/api
      - key: NODE_VERSION
        value: 18.x
      - key: NODE_ENV
        value: production
    healthCheckPath: /
    autoDeploy: true

  # Backend service
  - type: web
    name: salary-slips-automation
    env: python
    region: oregon
    plan: free
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: FLASK_APP
        value: app.py
      - key: FLASK_ENV
        value: production
      - key: PYTHONPATH
        value: /opt/render/project/src/backend
    healthCheckPath: /healthz
    autoDeploy: true 