services:
  # Frontend service
  - type: web
    name: be-ss-automation-frontend
    env: docker
    region: singapore
    plan: free
    dockerContext: ./frontend
    dockerfilePath: ./frontend/Dockerfile
    envVars:
      - key: VITE_API_URL
        value: https://be-ss-automation.onrender.com/api
      - key: NODE_VERSION
        value: 18.x
      - key: NODE_ENV
        value: production
    secretFiles:
      - name: config.js
        mountPath: /app/src/config.js
    healthCheckPath: /
    autoDeploy: true

  # Backend service
  - type: web
    name: salary-slips-automation
    env: python
    region: oregon
    plan: free
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: FLASK_APP
        value: app.py
      - key: FLASK_ENV
        value: production
      - key: PYTHONPATH
        value: /opt/render/project/src/backend
      - key: GOOGLE_DRIVE_CREDENTIALS_PATH
        value: /etc/secrets/client_secrets.json
      - key: GOOGLE_SHEETS_CREDENTIALS_PATH
        value: /etc/secrets/service_account_credentials.json
      - key: GOOGLE_OAUTH2_PATH
        value: /etc/secrets/Oauth2.json
    secretFiles:
      - name: client_secrets.json
        mountPath: /etc/secrets/client_secrets.json
      - name: service_account_credentials.json
        mountPath: /etc/secrets/service_account_credentials.json
      - name: Oauth2.json
        mountPath: /etc/secrets/Oauth2.json
    healthCheckPath: /healthz
    autoDeploy: true 